<!DOCTYPE html>



  


<html class="theme-next pisces use-motion" lang="zh-Hans">
<head>
  <!-- hexo-inject:begin --><!-- hexo-inject:end --><meta charset="UTF-8"/>
<meta http-equiv="X-UA-Compatible" content="IE=edge" />
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1"/>
<meta name="theme-color" content="#222">









<meta http-equiv="Cache-Control" content="no-transform" />
<meta http-equiv="Cache-Control" content="no-siteapp" />
















  
  
  <link href="/lib/fancybox/source/jquery.fancybox.css?v=2.1.5" rel="stylesheet" type="text/css" />







<link href="/lib/font-awesome/css/font-awesome.min.css?v=4.6.2" rel="stylesheet" type="text/css" />

<link href="/css/main.css?v=5.1.3" rel="stylesheet" type="text/css" />


  <link rel="apple-touch-icon" sizes="180x180" href="/images/apple-touch-icon-next.png?v=5.1.3">


  <link rel="icon" type="image/png" sizes="32x32" href="/images/favicon-32x32-next.png?v=5.1.3">


  <link rel="icon" type="image/png" sizes="16x16" href="/images/favicon-16x16-next.png?v=5.1.3">


  <link rel="mask-icon" href="/images/logo.svg?v=5.1.3" color="#222">





  <meta name="keywords" content="生物信息学," />










<meta name="description" content="异常的概念 程序在运行时，如果Python解释器遇到了一个错误，Python解释器就会停止程序的执行，并且提示一些错误信息，这就是异常。 程序停止执行并提示错误信息的这个动作我们称之为抛出异常。 现在我们来了解一下Python为什么会抛出异常，看一个简单的案例： 12345678In [6]: num = int(input(&quot;请输入一个数字  &quot;))请输入一个数字  a---------">
<meta name="keywords" content="生物信息学">
<meta property="og:type" content="article">
<meta property="og:title" content="Python学习笔记（15）-黑马教程-异常">
<meta property="og:url" content="http://rvdsd.top/2018/04/16/Python/Python学习笔记（15）-异常/index.html">
<meta property="og:site_name" content="RVDSD的个人笔记本">
<meta property="og:description" content="异常的概念 程序在运行时，如果Python解释器遇到了一个错误，Python解释器就会停止程序的执行，并且提示一些错误信息，这就是异常。 程序停止执行并提示错误信息的这个动作我们称之为抛出异常。 现在我们来了解一下Python为什么会抛出异常，看一个简单的案例： 12345678In [6]: num = int(input(&quot;请输入一个数字  &quot;))请输入一个数字  a---------">
<meta property="og:locale" content="zh-Hans">
<meta property="og:image" content="https://pic-1256416512.cos.ap-chengdu.myqcloud.com/img/20190607220308.png">
<meta property="og:image" content="https://pic-1256416512.cos.ap-chengdu.myqcloud.com/img/20190607233243.png">
<meta property="og:updated_time" content="2019-06-07T15:50:12.751Z">
<meta name="twitter:card" content="summary">
<meta name="twitter:title" content="Python学习笔记（15）-黑马教程-异常">
<meta name="twitter:description" content="异常的概念 程序在运行时，如果Python解释器遇到了一个错误，Python解释器就会停止程序的执行，并且提示一些错误信息，这就是异常。 程序停止执行并提示错误信息的这个动作我们称之为抛出异常。 现在我们来了解一下Python为什么会抛出异常，看一个简单的案例： 12345678In [6]: num = int(input(&quot;请输入一个数字  &quot;))请输入一个数字  a---------">
<meta name="twitter:image" content="https://pic-1256416512.cos.ap-chengdu.myqcloud.com/img/20190607220308.png">



<script type="text/javascript" id="hexo.configurations">
  var NexT = window.NexT || {};
  var CONFIG = {
    root: '/',
    scheme: 'Pisces',
    version: '5.1.3',
    sidebar: {"position":"left","display":"post","offset":12,"b2t":false,"scrollpercent":false,"onmobile":false},
    fancybox: true,
    tabs: true,
    motion: {"enable":true,"async":false,"transition":{"post_block":"fadeIn","post_header":"slideDownIn","post_body":"slideDownIn","coll_header":"slideLeftIn","sidebar":"slideUpIn"}},
    duoshuo: {
      userId: '0',
      author: '博主'
    },
    algolia: {
      applicationID: '',
      apiKey: '',
      indexName: '',
      hits: {"per_page":10},
      labels: {"input_placeholder":"Search for Posts","hits_empty":"We didn't find any results for the search: ${query}","hits_stats":"${hits} results found in ${time} ms"}
    }
  };
</script>



  <link rel="canonical" href="http://rvdsd.top/2018/04/16/Python/Python学习笔记（15）-异常/"/>





  <title>Python学习笔记（15）-黑马教程-异常 | RVDSD的个人笔记本</title><!-- hexo-inject:begin --><!-- hexo-inject:end -->
  








</head>

<body itemscope itemtype="http://schema.org/WebPage" lang="zh-Hans">

  
  
    
  

  <!-- hexo-inject:begin --><!-- hexo-inject:end --><div class="container sidebar-position-left page-post-detail">
    <div class="headband"></div>

    <header id="header" class="header" itemscope itemtype="http://schema.org/WPHeader">
      <div class="header-inner"><div class="site-brand-wrapper">
  <div class="site-meta ">
    

    <div class="custom-logo-site-title">
      <a href="/"  class="brand" rel="start">
        <span class="logo-line-before"><i></i></span>
        <span class="site-title">RVDSD的个人笔记本</span>
        <span class="logo-line-after"><i></i></span>
      </a>
    </div>
      
        <p class="site-subtitle">学习过程中的输出</p>
      
  </div>

  <div class="site-nav-toggle">
    <button>
      <span class="btn-bar"></span>
      <span class="btn-bar"></span>
      <span class="btn-bar"></span>
    </button>
  </div>
</div>

<nav class="site-nav">
  

  
    <ul id="menu" class="menu">
      
        
        <li class="menu-item menu-item-home">
          <a href="/" rel="section">
            
              <i class="menu-item-icon fa fa-fw fa-home"></i> <br />
            
            首页
          </a>
        </li>
      
        
        <li class="menu-item menu-item-about">
          <a href="/about/" rel="section">
            
              <i class="menu-item-icon fa fa-fw fa-user"></i> <br />
            
            关于
          </a>
        </li>
      
        
        <li class="menu-item menu-item-tags">
          <a href="/tags/" rel="section">
            
              <i class="menu-item-icon fa fa-fw fa-tags"></i> <br />
            
            标签
          </a>
        </li>
      
        
        <li class="menu-item menu-item-categories">
          <a href="/categories/" rel="section">
            
              <i class="menu-item-icon fa fa-fw fa-th"></i> <br />
            
            分类
          </a>
        </li>
      
        
        <li class="menu-item menu-item-archives">
          <a href="/archives/" rel="section">
            
              <i class="menu-item-icon fa fa-fw fa-archive"></i> <br />
            
            归档
          </a>
        </li>
      

      
    </ul>
  

  
</nav>



 </div>
    </header>

    <main id="main" class="main">
      <div class="main-inner">
        <div class="content-wrap">
          <div id="content" class="content">
            

  <div id="posts" class="posts-expand">
    

  

  
  
  

  <article class="post post-type-tags" itemscope itemtype="http://schema.org/Article">
  
  
  
  <div class="post-block">
    <link itemprop="mainEntityOfPage" href="http://rvdsd.top/2018/04/16/Python/Python学习笔记（15）-异常/">

    <span hidden itemprop="author" itemscope itemtype="http://schema.org/Person">
      <meta itemprop="name" content="RVDSD">
      <meta itemprop="description" content="">
      <meta itemprop="image" content="/images/avatar.gif">
    </span>

    <span hidden itemprop="publisher" itemscope itemtype="http://schema.org/Organization">
      <meta itemprop="name" content="RVDSD的个人笔记本">
    </span>

    
      <header class="post-header">

        
        
          <h1 class="post-title" itemprop="name headline">Python学习笔记（15）-黑马教程-异常</h1>
        

        <div class="post-meta">
          <span class="post-time">
            
              <span class="post-meta-item-icon">
                <i class="fa fa-calendar-o"></i>
              </span>
              
                <span class="post-meta-item-text">发表于</span>
              
              <time title="创建于" itemprop="dateCreated datePublished" datetime="2018-04-16T12:00:00+08:00">
                2018-04-16
              </time>
            

            

            
          </span>

          
            <span class="post-category" >
            
              <span class="post-meta-divider">|</span>
            
              <span class="post-meta-item-icon">
                <i class="fa fa-folder-o"></i>
              </span>
              
                <span class="post-meta-item-text">分类于</span>
              
              
                <span itemprop="about" itemscope itemtype="http://schema.org/Thing">
                  <a href="/categories/Python/" itemprop="url" rel="index">
                    <span itemprop="name">Python</span>
                  </a>
                </span>

                
                
              
            </span>
          

          
            
          

          
          

          

          
            <div class="post-wordcount">
              
                
                  <span class="post-meta-divider">|</span>
                
                <span class="post-meta-item-icon">
                  <i class="fa fa-file-word-o"></i>
                </span>
                
                  <span class="post-meta-item-text">字数统计&#58;</span>
                
                <span title="字数统计">
                  4,682
                </span>
              

              
                <span class="post-meta-divider">|</span>
              

              
                <span class="post-meta-item-icon">
                  <i class="fa fa-clock-o"></i>
                </span>
                
                  <span class="post-meta-item-text">阅读时长 &asymp;</span>
                
                <span title="阅读时长">
                  18
                </span>
              
            </div>
          

          

        </div>
      </header>
    

    
    
    
    <div class="post-body" itemprop="articleBody">

      
      

      
        <h2 id="异常的概念">异常的概念</h2>
<p>程序在运行时，如果<code>Python解释器</code>遇到了一个错误，Python解释器就会停止程序的执行，并且提示一些错误信息，这就是<strong>异常</strong>。</p>
<p>程序停止执行并提示错误信息的这个动作我们称之为<strong>抛出异常</strong>。</p>
<p>现在我们来了解一下Python为什么会抛出异常，看一个简单的案例：</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><div class="line">1</div><div class="line">2</div><div class="line">3</div><div class="line">4</div><div class="line">5</div><div class="line">6</div><div class="line">7</div><div class="line">8</div></pre></td><td class="code"><pre><div class="line">In [<span class="number">6</span>]: num = int(input(<span class="string">"请输入一个数字  "</span>))</div><div class="line">请输入一个数字  a</div><div class="line">---------------------------------------------------------------------------</div><div class="line">ValueError                                Traceback (most recent call last)</div><div class="line">&lt;ipython-input<span class="number">-6</span>-f1f596245a67&gt; <span class="keyword">in</span> &lt;module&gt;()</div><div class="line">----&gt; 1 num = int(input("请输入一个数字  "))</div><div class="line"></div><div class="line">ValueError: invalid literal <span class="keyword">for</span> int() <span class="keyword">with</span> base <span class="number">10</span>: <span class="string">'a'</span></div></pre></td></tr></table></figure>
<p>在这个案例中，我们先输入了一段代码，用于接收用户输入的整数，即<code>num = int(input(&quot;请输入一个数字  &quot;))</code>，但是当我们输入了一个<code>a</code>后，Python的解释器就报错了，并且解释器提示，输入的这个<code>a</code>无法用于<code>int()</code>函数，它只支持10进行的转换，这就是抛出异常。这说明，即使我们输入的是一段在语法上正确的代码，但是它在执行上还有可能报错的，因为我们无法判断用户在输入内容上，用户输入的是一个数字还是字母。</p>
<p>因此当我们面临类似的情况时，我们就需要处理这种特殊情况，我们看一下示意图：</p>
<div class="figure">
<img src="https://pic-1256416512.cos.ap-chengdu.myqcloud.com/img/20190607220308.png">

</div>
<p>从示意图上我们可以知道，当程序遇到错误时，会抛出异常，这个异常就是我们在设计程序时需要考虑到的情况，这种情况是抛给最初设计程序的程序员的，程序员会针对这种情况输出一定的反馈信息，例如，我们设计程序时，如果有输入性别的选项，有人输入了一个数字，那么就是错误的，程序需要针对这种情况提前设计相应的反馈信息。</p>
<h2 id="捕获异常语法">捕获异常语法</h2>
<p>在程序开发中，如果对某些代码执行不能确定是否正确，可以增加<code>try</code>来捕获异常，捕获异常最简单的语法格式如下所示：</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><div class="line">1</div><div class="line">2</div><div class="line">3</div><div class="line">4</div></pre></td><td class="code"><pre><div class="line"><span class="keyword">try</span>:</div><div class="line">    尝试执行的代码</div><div class="line"><span class="keyword">except</span>:</div><div class="line">    出现错误的处理</div></pre></td></tr></table></figure>
<p>这里解释一下：<code>try</code>是指下方编写要尝试执行的代码，也就是那些<strong>不确定是否能够正常执行的代码</strong>。<code>except</code>指的是，<code>try</code>下方执行失败后，需要执行哪些代码。</p>
<h3 id="捕获异常的案例">捕获异常的案例</h3>
<p>现在还是看前面的那个案例，如下所示：</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><div class="line">1</div></pre></td><td class="code"><pre><div class="line">num = int(input(<span class="string">"请输入一个整数： "</span>))</div></pre></td></tr></table></figure>
<p>现在我们输入一个<code>4</code>，结果如下所示：</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><div class="line">1</div></pre></td><td class="code"><pre><div class="line">请输入一个整数： <span class="number">4</span></div></pre></td></tr></table></figure>
<p>这种情况下，程序运行是正常的，现在我们输入一个<code>a</code>，程序运行结果如下所示：</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><div class="line">1</div><div class="line">2</div><div class="line">3</div><div class="line">4</div><div class="line">5</div></pre></td><td class="code"><pre><div class="line">请输入一个整数： a</div><div class="line">Traceback (most recent call last):</div><div class="line">  File <span class="string">"D:/netdisk/bioinfo.notes/Python/黑马教程笔记/异常/hm_01_简单的异常捕获.py"</span>, line <span class="number">1</span>, <span class="keyword">in</span> &lt;module&gt;</div><div class="line">    num = int(input(<span class="string">"请输入一个整数： "</span>))</div><div class="line">ValueError: invalid literal <span class="keyword">for</span> int() <span class="keyword">with</span> base <span class="number">10</span>: <span class="string">'a'</span></div></pre></td></tr></table></figure>
<p>程序运行出错。</p>
<p>上面还是原来的内容，现在我们使用<code>try...except...</code>语法实现一下类似的功能，如下所示：</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><div class="line">1</div><div class="line">2</div><div class="line">3</div><div class="line">4</div><div class="line">5</div><div class="line">6</div><div class="line">7</div></pre></td><td class="code"><pre><div class="line"><span class="keyword">try</span>:</div><div class="line">    num = int(input(<span class="string">"请输入一个整数： "</span>))</div><div class="line"></div><div class="line"><span class="keyword">except</span>:</div><div class="line">    print(<span class="string">"请输入正确的整数： "</span>)</div><div class="line"></div><div class="line">print(<span class="string">"-"</span> *<span class="number">50</span>)</div></pre></td></tr></table></figure>
<p>现在我们输入一个<code>4</code>结果如下所示：</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><div class="line">1</div><div class="line">2</div></pre></td><td class="code"><pre><div class="line">请输入一个整数： <span class="number">4</span></div><div class="line">--------------------------------------------------</div></pre></td></tr></table></figure>
<p>现在我们输入一个<code>a</code>，结果如下所示：</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><div class="line">1</div><div class="line">2</div><div class="line">3</div></pre></td><td class="code"><pre><div class="line">请输入一个整数： a</div><div class="line">请输入正确的整数： </div><div class="line">--------------------------------------------------</div></pre></td></tr></table></figure>
<p>现在我们发现了，<code>except</code>下面的代码得到了执行。并且两种情况下，最后一行代码，也就是<code>print(&quot;-&quot; * 50)</code>的执行不受影响。</p>
<h2 id="错误类型的捕获">错误类型的捕获</h2>
<p>在程序执行时，可能遇到<strong>不同类型的异常</strong>，并且需要<strong>针对不同类型的异常，做出不同的响应</strong>，这个时候就需要捕获错误类型了，这种情况下的语法格式如下所示：</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><div class="line">1</div><div class="line">2</div><div class="line">3</div><div class="line">4</div><div class="line">5</div><div class="line">6</div><div class="line">7</div><div class="line">8</div><div class="line">9</div><div class="line">10</div><div class="line">11</div></pre></td><td class="code"><pre><div class="line"><span class="keyword">try</span>:</div><div class="line">    <span class="comment"># 尝试执行的代码</span></div><div class="line">    <span class="keyword">pass</span></div><div class="line"><span class="keyword">except</span> 错误类型<span class="number">1</span>:</div><div class="line">    <span class="comment"># 针对错误类型1，对应的代码处理</span></div><div class="line">    <span class="keyword">pass</span></div><div class="line"><span class="keyword">except</span> (错误类型<span class="number">2</span>, 错误类型<span class="number">3</span>):</div><div class="line">    <span class="comment"># 针对错误类型2和3，对应的代码处理</span></div><div class="line">    <span class="keyword">pass</span></div><div class="line"><span class="keyword">except</span> Exception <span class="keyword">as</span> result:</div><div class="line">    print(<span class="string">"未知错误 %s"</span> % result)</div></pre></td></tr></table></figure>
<p>当<code>Python</code>解释器抛出异常时，最后一行错误信息的第一个单词，就是错误类型。</p>
<h3 id="异常类型捕获案例">异常类型捕获案例</h3>
<p>我们还以前面的让用户输入整数的案例为例说明一下：</p>
<p>这个程序的需求为：①提示用户输入一个整数；②使用<code>8</code>这个整数除以刚刚用户输入的整数并输出，代码如下所示：</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><div class="line">1</div><div class="line">2</div><div class="line">3</div><div class="line">4</div><div class="line">5</div><div class="line">6</div><div class="line">7</div></pre></td><td class="code"><pre><div class="line"><span class="comment"># 提示用户输入一个整数</span></div><div class="line">num = int(input(<span class="string">"输入一个整数： "</span>))</div><div class="line"></div><div class="line"></div><div class="line"><span class="comment"># 使用 8 除以用户输入的整数并输入</span></div><div class="line">result = <span class="number">8</span>/num</div><div class="line">print(result)</div></pre></td></tr></table></figure>
<p>现在我们输入一个<code>10</code>，看一下运行结果，如下所示：</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><div class="line">1</div><div class="line">2</div></pre></td><td class="code"><pre><div class="line">输入一个整数： <span class="number">10</span></div><div class="line"><span class="number">0.8</span></div></pre></td></tr></table></figure>
<p>现在我们再输入一个字母<code>a</code>，我们看一下结果，结果会出错：</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><div class="line">1</div><div class="line">2</div><div class="line">3</div><div class="line">4</div><div class="line">5</div></pre></td><td class="code"><pre><div class="line">输入一个整数： a</div><div class="line">Traceback (most recent call last):</div><div class="line">  File <span class="string">"D:/netdisk/bioinfo.notes/Python/黑马教程笔记/异常/hm_02_捕获错误类型.py"</span>, line <span class="number">2</span>, <span class="keyword">in</span> &lt;module&gt;</div><div class="line">    num = int(input(<span class="string">"输入一个整数： "</span>))</div><div class="line">ValueError: invalid literal <span class="keyword">for</span> int() <span class="keyword">with</span> base <span class="number">10</span>: <span class="string">'a'</span></div></pre></td></tr></table></figure>
<p>但是，这个程序还有可能在<code>num</code>这个地方出错，因为如果用户输入的是一个<code>0</code>，那么<code>result = 8 / num</code>中除数就是0了，没有意义，如下所示：</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><div class="line">1</div><div class="line">2</div><div class="line">3</div><div class="line">4</div><div class="line">5</div></pre></td><td class="code"><pre><div class="line">输入一个整数： <span class="number">0</span></div><div class="line">Traceback (most recent call last):</div><div class="line">  File <span class="string">"D:/netdisk/bioinfo.notes/Python/黑马教程笔记/异常/hm_02_捕获错误类型.py"</span>, line <span class="number">6</span>, <span class="keyword">in</span> &lt;module&gt;</div><div class="line">    result = <span class="number">8</span>/num</div><div class="line">ZeroDivisionError: division by zero</div></pre></td></tr></table></figure>
<p>因此针对上面的这些情况，我们都要考虑到这些异常的具体情况，针对每一种具体情况来进行设计。</p>
<p>现在我们还需要了解一点就是，我们如何知道错误类型，前面我们提到，当Python解释器抛出异常时，最后一行错误信息的第一个单词，就是错误类型，现在我们具体的来看一下：</p>
<p>前面的2种错误的第一个单词分别是<code>ValueError</code>和<code>ZeroDivisionError</code>，这就是错误类型，现在我们将这个错误类型添加到代码中，如下所示：</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><div class="line">1</div><div class="line">2</div><div class="line">3</div><div class="line">4</div><div class="line">5</div><div class="line">6</div><div class="line">7</div><div class="line">8</div><div class="line">9</div><div class="line">10</div><div class="line">11</div></pre></td><td class="code"><pre><div class="line"><span class="keyword">try</span>:</div><div class="line">    <span class="comment"># 提示用户输入一个整数</span></div><div class="line">    num = int(input(<span class="string">"输入一个整数： "</span>))</div><div class="line"></div><div class="line"></div><div class="line">    <span class="comment"># 使用 8 除以用户输入的整数并输入</span></div><div class="line">    result = <span class="number">8</span>/num</div><div class="line">    print(result)</div><div class="line"></div><div class="line"><span class="keyword">except</span> ZeroDivisionError:</div><div class="line">    print(<span class="string">"除0错误"</span>)</div></pre></td></tr></table></figure>
<p>运行代码，我们输入一个<code>0</code>，结果如下所示：</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><div class="line">1</div><div class="line">2</div></pre></td><td class="code"><pre><div class="line">输入一个整数： <span class="number">0</span></div><div class="line">除<span class="number">0</span>错误</div></pre></td></tr></table></figure>
<p>当我们添加了这些代码后，Python解释器就会抛出异常了。</p>
<p>现在我们再来设计针对输入字母这种情况，如下所示：</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><div class="line">1</div><div class="line">2</div><div class="line">3</div><div class="line">4</div><div class="line">5</div><div class="line">6</div><div class="line">7</div><div class="line">8</div><div class="line">9</div><div class="line">10</div><div class="line">11</div><div class="line">12</div><div class="line">13</div><div class="line">14</div></pre></td><td class="code"><pre><div class="line"><span class="keyword">try</span>:</div><div class="line">    <span class="comment"># 提示用户输入一个整数</span></div><div class="line">    num = int(input(<span class="string">"输入一个整数： "</span>))</div><div class="line"></div><div class="line"></div><div class="line">    <span class="comment"># 使用 8 除以用户输入的整数并输入</span></div><div class="line">    result = <span class="number">8</span>/num</div><div class="line">    print(result)</div><div class="line"></div><div class="line"><span class="keyword">except</span> ZeroDivisionError:</div><div class="line">    print(<span class="string">"除0错误"</span>)</div><div class="line"></div><div class="line"><span class="keyword">except</span> ValueError:</div><div class="line">    print(<span class="string">"输入的不是整数"</span>)</div></pre></td></tr></table></figure>
<p>现在我们运行代码，输入一个字母<code>a</code>，如下所示：</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><div class="line">1</div><div class="line">2</div></pre></td><td class="code"><pre><div class="line">输入一个整数： a</div><div class="line">输入的不是整数</div></pre></td></tr></table></figure>
<p>这个案例说明了针对不止一种错误类型的处理方式。</p>
<h3 id="捕获未知错误">捕获未知错误</h3>
<p>在开发中，我们要预判到所有可能出现的错误有一定难度。如果希望程序无论出现任何错误，都<strong>不会因为Python解释器抛出异常而被终止</strong>，我们可能再增加一个except，如下所示：</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><div class="line">1</div><div class="line">2</div></pre></td><td class="code"><pre><div class="line"><span class="keyword">except</span> Exception <span class="keyword">as</span> result:</div><div class="line">    print(<span class="string">"未知错误 %s"</span> % result)</div></pre></td></tr></table></figure>
<p>现在我们把前面的案例中的那个除数为0的错误删除，使用这种未知错误来写一下，如下所示：</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><div class="line">1</div><div class="line">2</div><div class="line">3</div><div class="line">4</div><div class="line">5</div><div class="line">6</div><div class="line">7</div><div class="line">8</div><div class="line">9</div><div class="line">10</div><div class="line">11</div><div class="line">12</div><div class="line">13</div><div class="line">14</div></pre></td><td class="code"><pre><div class="line"><span class="keyword">try</span>:</div><div class="line">    <span class="comment"># 提示用户输入一个整数</span></div><div class="line">    num = int(input(<span class="string">"输入一个整数： "</span>))</div><div class="line"></div><div class="line"></div><div class="line">    <span class="comment"># 使用 8 除以用户输入的整数并输入</span></div><div class="line">    result = <span class="number">8</span>/num</div><div class="line">    print(result)</div><div class="line"></div><div class="line"><span class="keyword">except</span> ValueError:</div><div class="line">    print(<span class="string">"输入的不是整数"</span>)</div><div class="line"></div><div class="line"><span class="keyword">except</span> Exception <span class="keyword">as</span> result:</div><div class="line">    print(<span class="string">"未知错误 %s"</span> % result)</div></pre></td></tr></table></figure>
<p>运行结果如下所示：</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><div class="line">1</div><div class="line">2</div></pre></td><td class="code"><pre><div class="line">输入一个整数： <span class="number">0</span></div><div class="line">未知错误 division by zero</div></pre></td></tr></table></figure>
<p>因此，在捕获异常时，最好在最后加上这么这么一句，即<code>except Exception as result:</code>，其中<code>Exception</code>是Python是有关错误的一个类。</p>
<h2 id="异常捕获的完整语法">异常捕获的完整语法</h2>
<p>在实际开发中，为了能够处理复杂的异常情况，完整的异常语法如下所示：</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><div class="line">1</div><div class="line">2</div><div class="line">3</div><div class="line">4</div><div class="line">5</div><div class="line">6</div><div class="line">7</div><div class="line">8</div><div class="line">9</div><div class="line">10</div><div class="line">11</div><div class="line">12</div><div class="line">13</div><div class="line">14</div><div class="line">15</div><div class="line">16</div><div class="line">17</div><div class="line">18</div><div class="line">19</div><div class="line">20</div><div class="line">21</div></pre></td><td class="code"><pre><div class="line"><span class="keyword">try</span>:</div><div class="line">    <span class="comment"># 尝试执行的代码</span></div><div class="line">    <span class="keyword">pass</span></div><div class="line"><span class="keyword">except</span> 错误类型<span class="number">1</span>:</div><div class="line">    <span class="comment"># 针对错误类型1，对应的代码处理</span></div><div class="line">    <span class="keyword">pass</span></div><div class="line"><span class="keyword">except</span> 错误类型<span class="number">2</span>:</div><div class="line">    <span class="comment"># 针对错误类型2，对应的代码处理</span></div><div class="line">    <span class="keyword">pass</span></div><div class="line"><span class="keyword">except</span> (错误类型<span class="number">3</span>，错误类型<span class="number">4</span>):</div><div class="line">    <span class="comment"># 针对错误类型3和4，对应的代码处理</span></div><div class="line">    <span class="keyword">pass</span></div><div class="line"><span class="keyword">except</span> Exception <span class="keyword">as</span> result:</div><div class="line">    <span class="comment"># 打印错误信息</span></div><div class="line">    print(result)</div><div class="line"><span class="keyword">else</span>:</div><div class="line">    <span class="comment"># 没有异常才会执行的代码</span></div><div class="line">    <span class="keyword">pass</span></div><div class="line"><span class="keyword">finally</span>:</div><div class="line">    <span class="comment"># 无论是否有异常，都会执行的代码</span></div><div class="line">    print(<span class="string">"无论是否有异常，都会执行的代码"</span>)</div></pre></td></tr></table></figure>
<p>其中：</p>
<ul>
<li><code>else</code>只有在没有异常时才会执行的代码；</li>
<li><code>finally</code>无论是否有异常，都会执行的代码。</li>
</ul>
<p>现在我们求救一下前面案例的<strong>完整捕获异常</strong>，代码如下所示：</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><div class="line">1</div><div class="line">2</div><div class="line">3</div><div class="line">4</div><div class="line">5</div><div class="line">6</div><div class="line">7</div><div class="line">8</div><div class="line">9</div><div class="line">10</div><div class="line">11</div><div class="line">12</div><div class="line">13</div><div class="line">14</div><div class="line">15</div><div class="line">16</div><div class="line">17</div><div class="line">18</div><div class="line">19</div><div class="line">20</div></pre></td><td class="code"><pre><div class="line"><span class="keyword">try</span>:</div><div class="line">    <span class="comment"># 提示用户输入一个整数</span></div><div class="line">    num = int(input(<span class="string">"输入一个整数： "</span>))</div><div class="line"></div><div class="line"></div><div class="line">    <span class="comment"># 使用 8 除以用户输入的整数并输入</span></div><div class="line">    result = <span class="number">8</span>/num</div><div class="line">    print(result)</div><div class="line"></div><div class="line"><span class="keyword">except</span> ValueError:</div><div class="line">    print(<span class="string">"输入的不是整数"</span>)</div><div class="line"></div><div class="line"><span class="keyword">except</span> Exception <span class="keyword">as</span> result:</div><div class="line">    print(<span class="string">"未知错误 %s"</span> % result)</div><div class="line"><span class="keyword">else</span>:</div><div class="line">    print(<span class="string">"尝试成功"</span>)</div><div class="line"><span class="keyword">finally</span>:</div><div class="line">    print(<span class="string">"无论是否出现错误，都会执行的代码"</span>)</div><div class="line"></div><div class="line">print(<span class="string">"-"</span> * <span class="number">50</span>)</div></pre></td></tr></table></figure>
<p>现在我们输入数字<code>1</code>，结果如下所示：</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><div class="line">1</div><div class="line">2</div><div class="line">3</div><div class="line">4</div><div class="line">5</div></pre></td><td class="code"><pre><div class="line">输入一个整数： <span class="number">1</span></div><div class="line"><span class="number">8.0</span></div><div class="line">尝试成功</div><div class="line">无论是否出现错误，都会执行的代码</div><div class="line">--------------------------------------------------</div></pre></td></tr></table></figure>
<p>从结果中我们可以发现，在没有错误出现的情况下，<code>else</code>与<code>finally</code>下面的代码都得到了执行。</p>
<p>现在我们输入数字<code>0</code>，结果如下所示：</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><div class="line">1</div><div class="line">2</div><div class="line">3</div><div class="line">4</div></pre></td><td class="code"><pre><div class="line">输入一个整数： <span class="number">0</span></div><div class="line">未知错误 division by zero</div><div class="line">无论是否出现错误，都会执行的代码</div><div class="line">--------------------------------------------------</div></pre></td></tr></table></figure>
<p>从结果中我们可以发现，在出现错误出现的情况下，<code>else</code>下面的代码<strong>不执行</strong>，直接输出异常情况下的错误信息，并且<code>finally</code>下面的代码也得到了执行，因为<code>finally</code>下面的代码无论什么情况下都会执行，并且最后一行的代码<code>print(&quot;-&quot; * 50)</code>也得到了执行，因为抛出异常的完整代码部分就是从<code>try</code>开始，到<code>finally</code>结束，之后的代码就都正常执行了。</p>
<h2 id="异常的传递">异常的传递</h2>
<p>异常的传递是指，当<strong>函数/方法</strong>执行出现异常时，会将异常传递给函数/方法的调用一方，此时程序还不会被终止，如果传递到主程序，仍然没有异常处理，这个时候，程序才会被终止。</p>
<p>现在我们来验证一下异常的传递，先来看一下需求：</p>
<ol style="list-style-type: decimal">
<li>定义函数<code>demo1()</code>，提示用户输入一个整数并且返回；</li>
<li>定义函数<code>demo2()</code>，调用<code>demo1()</code>；</li>
<li>在主程序中调用<code>demo2()</code>。</li>
</ol>
<p>完整代码如下所示：</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><div class="line">1</div><div class="line">2</div><div class="line">3</div><div class="line">4</div></pre></td><td class="code"><pre><div class="line"><span class="function"><span class="keyword">def</span> <span class="title">demo1</span><span class="params">()</span>:</span></div><div class="line">    <span class="keyword">return</span> int(input(<span class="string">"输入整数： "</span>))</div><div class="line"></div><div class="line">print(demo1())</div></pre></td></tr></table></figure>
<p>运行程序，我们输入一个<code>1</code>，结果如下所示：</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><div class="line">1</div><div class="line">2</div></pre></td><td class="code"><pre><div class="line">输入整数： <span class="number">1</span></div><div class="line"><span class="number">1</span></div></pre></td></tr></table></figure>
<p>程序运行正常。现在我们输入一个字母<code>a</code>，如下所示：</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><div class="line">1</div><div class="line">2</div><div class="line">3</div><div class="line">4</div><div class="line">5</div><div class="line">6</div><div class="line">7</div></pre></td><td class="code"><pre><div class="line">输入整数： a</div><div class="line">Traceback (most recent call last):</div><div class="line">  File <span class="string">"D:/netdisk/bioinfo.notes/Python/黑马教程笔记/异常/hm_05_异常的传递.py"</span>, line <span class="number">4</span>, <span class="keyword">in</span> &lt;module&gt;</div><div class="line">    print(demo1())</div><div class="line">  File <span class="string">"D:/netdisk/bioinfo.notes/Python/黑马教程笔记/异常/hm_05_异常的传递.py"</span>, line <span class="number">2</span>, <span class="keyword">in</span> demo1</div><div class="line">    <span class="keyword">return</span> int(input(<span class="string">"输入整数： "</span>))</div><div class="line">ValueError: invalid literal <span class="keyword">for</span> int() <span class="keyword">with</span> base <span class="number">10</span>: <span class="string">'a'</span></div></pre></td></tr></table></figure>
<p>程序报错，最下面的错误信息是<code>ValueError: invalid literal for int() with base 10: 'a'</code>，这是说明，输入的字母无法被<code>int()</code>函数识别。</p>
<p>我们再往上看，有<code>line 2, in demo1 return int(input(&quot;输入整数： &quot;))</code>字样，也就是说错误出现在了第2行，第2行在转换整数的时候出现了问题。但是，第2行代码出现问题的时候，会把异常交给第4行，也就是解释器出现的这个信息<code>line 4, in &lt;module&gt;     print(demo1())</code>。第4行代码是主程序，也就是<code>print(demo1())</code>，它是在调用第2行的函数，第2行代码本身是不做异常处理的，主程序中没有做异常处理，因此程序就终止了。</p>
<p>现在我们再改造一下原代码，如下所示：</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><div class="line">1</div><div class="line">2</div><div class="line">3</div><div class="line">4</div><div class="line">5</div><div class="line">6</div><div class="line">7</div><div class="line">8</div><div class="line">9</div></pre></td><td class="code"><pre><div class="line"><span class="function"><span class="keyword">def</span> <span class="title">demo1</span><span class="params">()</span>:</span></div><div class="line">    <span class="keyword">return</span> int(input(<span class="string">"输入整数： "</span>))</div><div class="line"></div><div class="line"></div><div class="line"><span class="function"><span class="keyword">def</span> <span class="title">demo2</span><span class="params">()</span>:</span></div><div class="line">    <span class="keyword">return</span> demo1()</div><div class="line"></div><div class="line"></div><div class="line">print(demo1())</div></pre></td></tr></table></figure>
<p>现在我们再输入一个字母<code>a</code>，如下所示：</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><div class="line">1</div><div class="line">2</div><div class="line">3</div><div class="line">4</div><div class="line">5</div><div class="line">6</div><div class="line">7</div><div class="line">8</div><div class="line">9</div></pre></td><td class="code"><pre><div class="line">输入整数： a</div><div class="line">Traceback (most recent call last):</div><div class="line">  File <span class="string">"D:/netdisk/bioinfo.notes/Python/黑马教程笔记/异常/hm_05_异常的传递.py"</span>, line <span class="number">9</span>, <span class="keyword">in</span> &lt;module&gt;</div><div class="line">    print(demo2())</div><div class="line">  File <span class="string">"D:/netdisk/bioinfo.notes/Python/黑马教程笔记/异常/hm_05_异常的传递.py"</span>, line <span class="number">6</span>, <span class="keyword">in</span> demo2</div><div class="line">    <span class="keyword">return</span> demo1()</div><div class="line">  File <span class="string">"D:/netdisk/bioinfo.notes/Python/黑马教程笔记/异常/hm_05_异常的传递.py"</span>, line <span class="number">2</span>, <span class="keyword">in</span> demo1</div><div class="line">    <span class="keyword">return</span> int(input(<span class="string">"输入整数： "</span>))</div><div class="line">ValueError: invalid literal <span class="keyword">for</span> int() <span class="keyword">with</span> base <span class="number">10</span>: <span class="string">'a'</span></div></pre></td></tr></table></figure>
<p>从错误信息中我们可以知道这些信息：</p>
<ol style="list-style-type: decimal">
<li>出错的代码还是第2行，提示demo1函数出现的问题；</li>
<li>错误信息往上，我们发现了第2行代码出错时，会把错误传递给第6行，因为第6行中的demo2()函数调用了demo1()函数，继续提示demo2出现了问题，但此时我们并没有在demo2内部针对异常进行处理，此时继续向上传递，传递到了第9行；</li>
<li>第9行传递到了主程序，也就是<code>print(deom2())</code>。</li>
</ol>
<p>从上面的结果我们可以知道，一旦出现异常，异常会一级一级向上传递，一直到主程序，直到主程序终止运行。</p>
<p>如果我们在实际设计程序中，如果在每一个函数中都设计异常处理，这样代码量会非常大，不现实。因此我们可以利用异常的传递性，可以在主程序中捕获异常即可，如下所示：</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><div class="line">1</div><div class="line">2</div><div class="line">3</div><div class="line">4</div><div class="line">5</div><div class="line">6</div><div class="line">7</div><div class="line">8</div><div class="line">9</div><div class="line">10</div><div class="line">11</div><div class="line">12</div></pre></td><td class="code"><pre><div class="line"><span class="function"><span class="keyword">def</span> <span class="title">demo1</span><span class="params">()</span>:</span></div><div class="line">    <span class="keyword">return</span> int(input(<span class="string">"输入整数： "</span>))</div><div class="line"></div><div class="line"></div><div class="line"><span class="function"><span class="keyword">def</span> <span class="title">demo2</span><span class="params">()</span>:</span></div><div class="line">    <span class="keyword">return</span> demo1()</div><div class="line"></div><div class="line"><span class="comment"># 利用异常的传递性，在主程序捕获异常</span></div><div class="line"><span class="keyword">try</span>:</div><div class="line">    print(demo2())</div><div class="line"><span class="keyword">except</span> Exception <span class="keyword">as</span> result:</div><div class="line">    print(<span class="string">"未知3错误 %s"</span> % result)</div></pre></td></tr></table></figure>
<p>现在运行程序，输入一个字母<code>a</code>，如下所示：</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><div class="line">1</div><div class="line">2</div></pre></td><td class="code"><pre><div class="line">输入整数： a</div><div class="line">未知错误 invalid literal <span class="keyword">for</span> int() <span class="keyword">with</span> base <span class="number">10</span>: <span class="string">'a'</span></div></pre></td></tr></table></figure>
<p>从结果中我们可以发现，我们只在主程序中添加了异常捕获，就不用在每个函数中对异常进行捕获了。</p>
<p>现在总结一下，利用异常的传递性在开发程序中的好处：可以将精力放在函数的代码逻辑上，不用花太多精力放在异常捕获上，只要函数开发完成，就可以在主程序中添加异常捕获。</p>
<h2 id="抛出异常">抛出异常</h2>
<p>在开发中，除了代码执行出错，Python解释会自己抛出异常之外。我们还可以根据应用程序特有的功能来主动抛出异常，现在我们来看一个案例。</p>
<p>例如我们要添加一个用户登录模块，里面有一个函数，这个函数的功能是：提示用户输入密码，如果长度少于8，那么就抛出异常，如下所示：</p>
<div class="figure">
<img src="https://pic-1256416512.cos.ap-chengdu.myqcloud.com/img/20190607233243.png">

</div>
<p>这里需要注意的是，当前这个函数<strong>只负责</strong>提示用户输入密码，如果密码长度不正确，需要其他的函数进行额外处理。</p>
<h3 id="抛出异常-1">抛出异常</h3>
<p>Python中提供了一个<code>Exception</code>异常类。在开发时，如果满足特定功能需求时，希望抛出异常，可以做两件事情：</p>
<ol style="list-style-type: decimal">
<li>创建一个<code>Exception</code>的<strong>对象</strong>；</li>
<li>使用<code>raise</code>关键字抛出<strong>异常对象</strong>。</li>
</ol>
<p>我们来看一下前面案例的需求：</p>
<ol style="list-style-type: decimal">
<li>定义<code>input_password</code>函数，提示用户输入密码；</li>
<li>如果用户输入长度小于8，抛出异常；</li>
<li>如果用户输入长度大于等于8，返回输入的密码。</li>
</ol>
<p>现在来看一下代码：</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><div class="line">1</div><div class="line">2</div><div class="line">3</div><div class="line">4</div><div class="line">5</div><div class="line">6</div><div class="line">7</div><div class="line">8</div><div class="line">9</div><div class="line">10</div><div class="line">11</div><div class="line">12</div><div class="line">13</div><div class="line">14</div><div class="line">15</div></pre></td><td class="code"><pre><div class="line"><span class="function"><span class="keyword">def</span> <span class="title">input_password</span><span class="params">()</span>:</span></div><div class="line"></div><div class="line">    <span class="comment"># 1. 提示用户输入密码</span></div><div class="line">    pwd = input(<span class="string">"请输入密码： "</span>)</div><div class="line"></div><div class="line">    <span class="comment"># 2. 判断密码长度 &gt;= 8， 返回用户输入的密码</span></div><div class="line">    <span class="keyword">if</span> len(pwd) &gt;= <span class="number">8</span>:</div><div class="line">        <span class="keyword">return</span> pwd</div><div class="line"></div><div class="line">    <span class="comment"># 3. 如果密码 &lt; 8，主动抛出异常</span></div><div class="line">    print(<span class="string">"主动抛出异常"</span>)</div><div class="line"></div><div class="line"></div><div class="line"><span class="comment"># 提示用户输入密码</span></div><div class="line">print(input_password())</div></pre></td></tr></table></figure>
<p>现在运行代码，我们输入12345678，结果如下所示：</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><div class="line">1</div><div class="line">2</div></pre></td><td class="code"><pre><div class="line">请输入密码： <span class="number">123456789</span></div><div class="line"><span class="number">123456789</span></div></pre></td></tr></table></figure>
<p>现在我们输入123，如下所示：</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><div class="line">1</div><div class="line">2</div><div class="line">3</div></pre></td><td class="code"><pre><div class="line">请输入密码： <span class="number">123</span></div><div class="line">主动抛出异常</div><div class="line"><span class="keyword">None</span></div></pre></td></tr></table></figure>
<p>从结果中我们可以发现，输出了异常，并且还有一个<code>None</code>，这里为什么会输出<code>None</code>呢，这是因为在代码中，抛出异常时，并没有任何返回，所以就返回了<code>None</code>。</p>
<p>现在再更改一下代码，需要创建一个<code>Exception</code>类对象，如下所示：</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><div class="line">1</div><div class="line">2</div><div class="line">3</div><div class="line">4</div><div class="line">5</div><div class="line">6</div><div class="line">7</div><div class="line">8</div><div class="line">9</div><div class="line">10</div><div class="line">11</div><div class="line">12</div><div class="line">13</div><div class="line">14</div><div class="line">15</div><div class="line">16</div><div class="line">17</div><div class="line">18</div><div class="line">19</div><div class="line">20</div><div class="line">21</div></pre></td><td class="code"><pre><div class="line"><span class="function"><span class="keyword">def</span> <span class="title">input_password</span><span class="params">()</span>:</span></div><div class="line"></div><div class="line">    <span class="comment"># 1. 提示用户输入密码</span></div><div class="line">    pwd = input(<span class="string">"请输入密码： "</span>)</div><div class="line"></div><div class="line">    <span class="comment"># 2. 判断密码长度 &gt;= 8， 返回用户输入的密码</span></div><div class="line">    <span class="keyword">if</span> len(pwd) &gt;= <span class="number">8</span>:</div><div class="line">        <span class="keyword">return</span> pwd</div><div class="line"></div><div class="line">    <span class="comment"># 3. 如果密码 &lt; 8，主动抛出异常</span></div><div class="line">    print(<span class="string">"主动抛出异常"</span>)</div><div class="line">    <span class="comment"># 第一步：创建异常对象</span></div><div class="line">    ex = Exception(<span class="string">"密码长度不够"</span>)</div><div class="line"></div><div class="line">    <span class="comment"># 第二步：主动抛出异常</span></div><div class="line">    <span class="keyword">raise</span> ex</div><div class="line"></div><div class="line"></div><div class="line"></div><div class="line"><span class="comment"># 提示用户输入密码</span></div><div class="line">print(input_password())</div></pre></td></tr></table></figure>
<p>运行结果，我们输入123，如下所示：</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><div class="line">1</div><div class="line">2</div><div class="line">3</div><div class="line">4</div><div class="line">5</div><div class="line">6</div><div class="line">7</div><div class="line">8</div></pre></td><td class="code"><pre><div class="line">请输入密码： <span class="number">123</span></div><div class="line">主动抛出异常</div><div class="line">Traceback (most recent call last):</div><div class="line">  File <span class="string">"D:/netdisk/bioinfo.notes/Python/黑马教程笔记/异常/hm_06_抛出异常.py"</span>, line <span class="number">21</span>, <span class="keyword">in</span> &lt;module&gt;</div><div class="line">    print(input_password())</div><div class="line">  File <span class="string">"D:/netdisk/bioinfo.notes/Python/黑马教程笔记/异常/hm_06_抛出异常.py"</span>, line <span class="number">16</span>, <span class="keyword">in</span> input_password</div><div class="line">    <span class="keyword">raise</span> ex</div><div class="line">Exception: 密码长度不够</div></pre></td></tr></table></figure>
<p>从结果我们可以看出现，程序出错的代码在第16行，也就是<code>raise ex</code>这一句。根据异常的传递性，继续向上看，异常传递到第22行，也就是<code>print(input_password())</code>这一句，此时我们使用try来改一下这句，如下所示：</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><div class="line">1</div><div class="line">2</div><div class="line">3</div><div class="line">4</div><div class="line">5</div><div class="line">6</div><div class="line">7</div><div class="line">8</div><div class="line">9</div><div class="line">10</div><div class="line">11</div><div class="line">12</div><div class="line">13</div><div class="line">14</div><div class="line">15</div><div class="line">16</div><div class="line">17</div><div class="line">18</div><div class="line">19</div><div class="line">20</div><div class="line">21</div><div class="line">22</div><div class="line">23</div><div class="line">24</div></pre></td><td class="code"><pre><div class="line"><span class="function"><span class="keyword">def</span> <span class="title">input_password</span><span class="params">()</span>:</span></div><div class="line"></div><div class="line">    <span class="comment"># 1. 提示用户输入密码</span></div><div class="line">    pwd = input(<span class="string">"请输入密码： "</span>)</div><div class="line"></div><div class="line">    <span class="comment"># 2. 判断密码长度 &gt;= 8， 返回用户输入的密码</span></div><div class="line">    <span class="keyword">if</span> len(pwd) &gt;= <span class="number">8</span>:</div><div class="line">        <span class="keyword">return</span> pwd</div><div class="line"></div><div class="line">    <span class="comment"># 3. 如果密码 &lt; 8，主动抛出异常</span></div><div class="line">    print(<span class="string">"主动抛出异常"</span>)</div><div class="line">    <span class="comment"># 第一步：创建异常对象-可以使用错误信息字符串作为参数</span></div><div class="line">    ex = Exception(<span class="string">"密码长度不够"</span>)</div><div class="line"></div><div class="line">    <span class="comment"># 第二步：主动抛出异常</span></div><div class="line">    <span class="keyword">raise</span> ex</div><div class="line"></div><div class="line"></div><div class="line"></div><div class="line"><span class="comment"># 提示用户输入密码</span></div><div class="line"><span class="keyword">try</span>:</div><div class="line">    print(input_password())</div><div class="line"><span class="keyword">except</span> Exception <span class="keyword">as</span> result:</div><div class="line">    print(result)</div></pre></td></tr></table></figure>
<p>继续运行，还是输入123，如下所示：</p>
<figure class="highlight python"><table><tr><td class="gutter"><pre><div class="line">1</div><div class="line">2</div><div class="line">3</div></pre></td><td class="code"><pre><div class="line">请输入密码： <span class="number">123</span></div><div class="line">主动抛出异常</div><div class="line">密码长度不够</div></pre></td></tr></table></figure>
<p>这一次我们就可以发现，运行正常。</p>
<p>在这个案例中我们其实就发现了，我们写了<code>Exception</code>这个类的对象，程序最终输出的结果就是我们定义的那个对象，即<code>ex = Exception(&quot;密码长度不够&quot;)</code>。</p>

      
    </div>
    
    
    

    

    

    

    <footer class="post-footer">
      
        <div class="post-tags">
          
            <a href="/tags/生物信息学/" <i class="fa fa-tag"></i> 生物信息学</a>
          
        </div>
      

      
      
      

      
        <div class="post-nav">
          <div class="post-nav-next post-nav-item">
            
              <a href="/2018/04/15/Python/Python学习笔记（14）-面向对象之多态和类属性/" rel="next" title="Python学习笔记（14）-黑马教程-面向对象之多态和类属性">
                <i class="fa fa-chevron-left"></i> Python学习笔记（14）-黑马教程-面向对象之多态和类属性
              </a>
            
          </div>

          <span class="post-nav-divider"></span>

          <div class="post-nav-prev post-nav-item">
            
              <a href="/2018/04/17/Python/Python学习笔记（16）-模块/" rel="prev" title="Python学习笔记（16）-黑马教程-模块与包">
                Python学习笔记（16）-黑马教程-模块与包 <i class="fa fa-chevron-right"></i>
              </a>
            
          </div>
        </div>
      

      
      
    </footer>
  </div>
  
  
  
  </article>



    <div class="post-spread">
      
    </div>
  </div>


          </div>
          


          

  
    <div class="comments" id="comments">
      <div id="vcomments"></div>
    </div>
  



        </div>
        
          
  
  <div class="sidebar-toggle">
    <div class="sidebar-toggle-line-wrap">
      <span class="sidebar-toggle-line sidebar-toggle-line-first"></span>
      <span class="sidebar-toggle-line sidebar-toggle-line-middle"></span>
      <span class="sidebar-toggle-line sidebar-toggle-line-last"></span>
    </div>
  </div>

  <aside id="sidebar" class="sidebar">
    
    <div class="sidebar-inner">

      

      
        <ul class="sidebar-nav motion-element">
          <li class="sidebar-nav-toc sidebar-nav-active" data-target="post-toc-wrap">
            文章目录
          </li>
          <li class="sidebar-nav-overview" data-target="site-overview-wrap">
            站点概览
          </li>
        </ul>
      

      <section class="site-overview-wrap sidebar-panel">
        <div class="site-overview">
          <div class="site-author motion-element" itemprop="author" itemscope itemtype="http://schema.org/Person">
            
              <p class="site-author-name" itemprop="name">RVDSD</p>
              <p class="site-description motion-element" itemprop="description"></p>
          </div>

          <nav class="site-state motion-element">

            
              <div class="site-state-item site-state-posts">
              
                <a href="/archives/">
              
                  <span class="site-state-item-count">166</span>
                  <span class="site-state-item-name">日志</span>
                </a>
              </div>
            

            
              
              
              <div class="site-state-item site-state-categories">
                <a href="/categories/index.html">
                  <span class="site-state-item-count">11</span>
                  <span class="site-state-item-name">分类</span>
                </a>
              </div>
            

            
              
              
              <div class="site-state-item site-state-tags">
                <a href="/tags/index.html">
                  <span class="site-state-item-count">46</span>
                  <span class="site-state-item-name">标签</span>
                </a>
              </div>
            

          </nav>

          

          <div class="links-of-author motion-element">
            
          </div>

          
          

          
          

          

        </div>
      </section>

      
      <!--noindex-->
        <section class="post-toc-wrap motion-element sidebar-panel sidebar-panel-active">
          <div class="post-toc">

            
              
            

            
              <div class="post-toc-content"><ol class="nav"><li class="nav-item nav-level-2"><a class="nav-link" href="#异常的概念"><span class="nav-number">1.</span> <span class="nav-text">异常的概念</span></a></li><li class="nav-item nav-level-2"><a class="nav-link" href="#捕获异常语法"><span class="nav-number">2.</span> <span class="nav-text">捕获异常语法</span></a><ol class="nav-child"><li class="nav-item nav-level-3"><a class="nav-link" href="#捕获异常的案例"><span class="nav-number">2.1.</span> <span class="nav-text">捕获异常的案例</span></a></li></ol></li><li class="nav-item nav-level-2"><a class="nav-link" href="#错误类型的捕获"><span class="nav-number">3.</span> <span class="nav-text">错误类型的捕获</span></a><ol class="nav-child"><li class="nav-item nav-level-3"><a class="nav-link" href="#异常类型捕获案例"><span class="nav-number">3.1.</span> <span class="nav-text">异常类型捕获案例</span></a></li><li class="nav-item nav-level-3"><a class="nav-link" href="#捕获未知错误"><span class="nav-number">3.2.</span> <span class="nav-text">捕获未知错误</span></a></li></ol></li><li class="nav-item nav-level-2"><a class="nav-link" href="#异常捕获的完整语法"><span class="nav-number">4.</span> <span class="nav-text">异常捕获的完整语法</span></a></li><li class="nav-item nav-level-2"><a class="nav-link" href="#异常的传递"><span class="nav-number">5.</span> <span class="nav-text">异常的传递</span></a></li><li class="nav-item nav-level-2"><a class="nav-link" href="#抛出异常"><span class="nav-number">6.</span> <span class="nav-text">抛出异常</span></a><ol class="nav-child"><li class="nav-item nav-level-3"><a class="nav-link" href="#抛出异常-1"><span class="nav-number">6.1.</span> <span class="nav-text">抛出异常</span></a></li></ol></li></ol></div>
            

          </div>
        </section>
      <!--/noindex-->
      

      

    </div>
  </aside>


        
      </div>
    </main>

    <footer id="footer" class="footer">
      <div class="footer-inner">
        <script async src="https://busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js"></script>

<div class="copyright">&copy; <span itemprop="copyrightYear">2019</span>
  <span class="with-love">
    <i class="fa fa-user"></i>
  </span>
  <span class="author" itemprop="copyrightHolder">RVDSD</span>

  
</div>



<div class="powered-by">
<i class="fa fa-user-md"></i><span id="busuanzi_container_site_pv">
  本站访客数:<span id="busuanzi_value_site_uv"></span>
</span>
</div>


  <div class="powered-by">由 <a class="theme-link" target="_blank" href="https://hexo.io">Hexo</a> 强力驱动</div>



  <span class="post-meta-divider">|</span>



  <div class="theme-info">主题 &mdash; <a class="theme-link" target="_blank" href="https://github.com/iissnan/hexo-theme-next">NexT.Pisces</a> v5.1.3</div>




<div class="theme-info">
  <div class="powered-by"></div>
  <span class="post-count">博客全站共630.8k字</span>
</div>

        







        
      </div>
    </footer>

    
      <div class="back-to-top">
        <i class="fa fa-arrow-up"></i>
        
      </div>
    

    

  </div>

  

<script type="text/javascript">
  if (Object.prototype.toString.call(window.Promise) !== '[object Function]') {
    window.Promise = null;
  }
</script>









  












  
  <script type="text/javascript" src="/lib/jquery/index.js?v=2.1.3"></script>

  
  <script type="text/javascript" src="/lib/fastclick/lib/fastclick.min.js?v=1.0.6"></script>

  
  <script type="text/javascript" src="/lib/jquery_lazyload/jquery.lazyload.js?v=1.9.7"></script>

  
  <script type="text/javascript" src="/lib/velocity/velocity.min.js?v=1.2.1"></script>

  
  <script type="text/javascript" src="/lib/velocity/velocity.ui.min.js?v=1.2.1"></script>

  
  <script type="text/javascript" src="/lib/fancybox/source/jquery.fancybox.pack.js?v=2.1.5"></script>


  


  <script type="text/javascript" src="/js/src/utils.js?v=5.1.3"></script>

  <script type="text/javascript" src="/js/src/motion.js?v=5.1.3"></script>



  
  


  <script type="text/javascript" src="/js/src/affix.js?v=5.1.3"></script>

  <script type="text/javascript" src="/js/src/schemes/pisces.js?v=5.1.3"></script>



  
  <script type="text/javascript" src="/js/src/scrollspy.js?v=5.1.3"></script>
<script type="text/javascript" src="/js/src/post-details.js?v=5.1.3"></script>



  


  <script type="text/javascript" src="/js/src/bootstrap.js?v=5.1.3"></script>



  


  




	





  





  












  





  

  

  
  

  
  
    <script type="text/x-mathjax-config">
      MathJax.Hub.Config({
        tex2jax: {
          inlineMath: [ ['$','$'], ["\\(","\\)"]  ],
          processEscapes: true,
          skipTags: ['script', 'noscript', 'style', 'textarea', 'pre', 'code']
        }
      });
    </script>

    <script type="text/x-mathjax-config">
      MathJax.Hub.Queue(function() {
        var all = MathJax.Hub.getAllJax(), i;
        for (i=0; i < all.length; i += 1) {
          all[i].SourceElement().parentNode.className += ' has-jax';
        }
      });
    </script>
    <script type="text/javascript" src="//cdn.bootcss.com/mathjax/2.7.1/latest.js?config=TeX-AMS-MML_HTMLorMML"></script><!-- hexo-inject:begin --><!-- Begin: Injected MathJax -->
<script type="text/x-mathjax-config">
  MathJax.Hub.Config("");
</script>

<script type="text/x-mathjax-config">
  MathJax.Hub.Queue(function() {
    var all = MathJax.Hub.getAllJax(), i;
    for(i=0; i < all.length; i += 1) {
      all[i].SourceElement().parentNode.className += ' has-jax';
    }
  });
</script>

<script type="text/javascript" src="custom_mathjax_source">
</script>
<!-- End: Injected MathJax -->
<!-- hexo-inject:end -->
  


  

  

</body>
</html>
